#ifndef PROTOCOL_UTILS_STATUS_HPP
#define PROTOCOL_UTILS_STATUS_HPP

#include <cstddef>
#include <cstdint>
#include <tuple>
#include <type_traits>
#include <utility>

namespace protocol
{

enum class Status : uint8_t
{
    OK = 0,        ///< Operation successful
    Error = 1,     ///< General/undefined error
    Timeout = 2,   ///< Operation timed out
    NotFound = 3, ///< Requested resource not found
    Overflow = 4,  ///< Buffer overflow or insufficient space
    RunOut = 5,    ///< No more resources available (e.g., memory, segments)
    Invalid = 6,   ///< Invalid argument or state
    Malformed = 7, ///< Malformed data or packet
    Busy = 8,       ///< Resource is busy or locked
    OutOfRange = 9, ///< Value is out of acceptable range
    NotSupported = 10, ///< Operation or feature not supported
    Refused = 11,     ///< Operation refused (e.g., due to policy or permissions)
    NotInitialized = 12, ///< Component or subsystem not initialized
    NothingToDo = 13, ///< No action required or nothing to do
};

inline constexpr
const char* getStatusName(Status status)
{
    switch(status) {
        case Status::OK: return "OK";
        case Status::Error: return "Error";
        case Status::Timeout: return "Timeout";
        case Status::NotFound: return "NotFound";
        case Status::Overflow: return "Overflow";
        case Status::RunOut: return "RunOut";
        case Status::Invalid: return "Invalid";
        case Status::Malformed: return "Malformed";
        case Status::Busy: return "Busy";
        case Status::OutOfRange: return "OutOfRange";
        case Status::NotSupported: return "NotSupported";
        case Status::Refused: return "Refused";
        case Status::NotInitialized: return "NotInitialized";
        case Status::NothingToDo: return "NothingToDo";
        default: return "Unknown";
    }
}

template<typename T>
class RetStatusRef;

template <typename T>
class RetStatus
{
public:
    RetStatus(Status status, const T &value) : status_(status), value_(value) {}

    RetStatus(Status status, T &&value) : status_(status), value_(std::move(value)) {}

    RetStatus(const RetStatus &other) = default;
    RetStatus &operator=(const RetStatus &other) = default;
    RetStatus(RetStatus &&other) = default;
    RetStatus &operator=(RetStatus &&other) = default;

    Status &getStatus()
    {
        return status_;
    }
    T &getValue()
    {
        return value_;
    }

    bool isOk() const
    {
        return status_ == Status::OK;
    }

    const T &getValueOr(const T &def_val) const
    {
        return isOk() ? value_ : def_val;
    }

private:
    Status status_;
    T value_;

    friend RetStatusRef<T>;
};

//// ACKNOWLEDGEMENT
//// Following code is generated by AI (thanks to ChatGPT)
//// I just copying all and adjust a little for my needs

template<typename T>
class RetStatusRef 
{
public:
    RetStatusRef(Status& status, T &value) : ref_status_(status), ref_value_(value) {}

    // assignment operator from lvalue RetStatusRef
    RetStatusRef& operator=(const RetStatus<T>& r) {
        ref_status_ = r.status_;
        ref_value_ = r.value_;
        return *this;
    }

    // assignment operator from rvalue RetStatusRef (move second)
    RetStatusRef& operator=(RetStatus<T>&& r) {
        ref_status_ = std::move(r.status_);
        ref_value_ = std::move(r.value_);
        return *this;
    }

    // Optional: assignment from another tie (for completeness)
    RetStatusRef& operator=(const RetStatusRef& t) {
        ref_status_ = t.ref_status_;
        ref_value_ = t.ref_status_;
        return *this;
    }

private:
    Status& ref_status_;
    T& ref_value_;
};

template<typename T>
RetStatusRef<T> tie(Status& a, T& b) {
    return RetStatusRef<T>(a, b);
}

}


#endif // PROTOCOL_UTILS_STATUS_HPP